# fly.toml app configuration file generated for interview-app-backend on 2024-07-16T23:29:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'interview-app-backend'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]

[env]
  RAILS_STORAGE = '/data'

[[mounts]]
  source = 'ruxtmin_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
